import './globals.css';
import { Syne } from 'next/font/google';
import Header from '../components/header';

const syne = Syne({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body className={`${syne.className} max-w-[95vw] mx-auto`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
